
package tampilan;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.mysql.cj.Query;
import java.lang.System.Logger.Level;
import java.sql.SQLException;
import java.util.logging.Logger;
import java.util.logging.Logger;
import javax.swing.UIManager;
import kelas.user;
        
/**
 *
 * @author Shifa
 */
public class frameuser extends javax.swing.JFrame {

    /**
     * Creates new form frameuser
     */
    public frameuser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        temail = new javax.swing.JTextField();
        tfullname = new javax.swing.JTextField();
        cstatus = new javax.swing.JComboBox<>();
        tusername = new javax.swing.JTextField();
        tpassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        temail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        temail.setForeground(new java.awt.Color(204, 204, 255));
        temail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        temail.setBorder(null);
        getContentPane().add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 110, 210, 30));

        tfullname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfullname.setForeground(new java.awt.Color(204, 204, 255));
        tfullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfullname.setBorder(null);
        getContentPane().add(tfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 200, 30));

        cstatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cstatus.setForeground(new java.awt.Color(204, 204, 255));
        cstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));
        cstatus.setBorder(null);
        cstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cstatusActionPerformed(evt);
            }
        });
        getContentPane().add(cstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 200, 40));

        tusername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tusername.setForeground(new java.awt.Color(204, 204, 255));
        tusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tusername.setBorder(null);
        getContentPane().add(tusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 42, 210, 30));

        tpassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tpassword.setForeground(new java.awt.Color(204, 204, 255));
        tpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tpassword.setBorder(null);
        getContentPane().add(tpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 162, 210, 30));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 140, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/User Name.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cstatusActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        try {
            user user = new user();
            
            user.setUser_name(tusername.getText());
            user.setUser_email(temail.getText());
            user.setUser_password(tpassword.getText());
            user.setUser_fullname(tfullname.getText());
            if (cstatus.getSelectedItem().equals("Aktif")) {
                user.setUser_status(1);
            } else {
                user.setUser_status(0);
            }
            user.tambahUser();
        } catch (SQLException sQLException) {
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
            UIManager.put("Button.arc",15);
            UIManager.put("TextComponent.arc", 15);
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tfullname;
    private javax.swing.JTextField tpassword;
    private javax.swing.JTextField tusername;
    // End of variables declaration//GEN-END:variables
}
